<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Theks.Shared\Theks.Shared.csproj" />
      <ProjectReference Include="..\Theks.Product.Domain\Theks.Product.Domain.csproj" />
    </ItemGroup>

</Project>
